#
# Goreleaser configuration.
#
# See also: .github/workflows/build.yml

version: 2

project_name: ha-addon

# https://goreleaser.com/customization/build
builds:
  - id: weather_build
    dir: weather/data
    binary: weather
    hooks:
      pre:
        - cmd: go mod tidy
          dir: weather/data
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - arm64   # for aarch64
      - amd64   # for amd64
      - "386"   # for i386
      - arm     # for armhf/armv7
    goarm:
      - 6       # commonly maps to armel/armhf (v6)
      - 7       # commonly maps to armv7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.binary={{ .Binary }} -X main.githubUrl={{ .GitURL }}/{{ .ProjectName }} -X main.builtBy=goreleaser

# Config the archives filenames, format, and other options.
# https://goreleaser.com/customization/archive
archives:
  - id: weather_archive
    formats: [tar.gz]
    ids:
      - weather_build
    # Disable the wrapping parent folder
    wrap_in_directory: false
    # Strip any subdirectories from the binary itself
    strip_binary_directory: true
    builds_info:
      mtime: "{{ .CommitTimestamp }}"
    # name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}{{ if eq .Arm "6" }}armhf{{ else }}armv7{{ end }}
      {{- else }}{{ .Arch }}{{ end }}
    # mapping:
    #   amd64: amd64      # Already matches
    #   386: i386        # Maps '386' to 'i386'
    #   arm64: aarch64   # Maps 'arm64' to 'aarch64'
    #   armv6: armhf     # Optional: maps arm v6 to armhf
    #   armv7: armv7     # Optional: explicitly name v7

    # use zip for windows archives
    format_overrides:
      - formats: [ 'zip' ]
        goos: windows

# Config the checksum filename
# https://goreleaser.com/customization/checksum
checksum:
  name_template: "checksums.txt"

# Changelog configuration (will be in the github release).
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  # paths:
  #   - weather/

# A footer to add to all releases.
release:
  # draft: false             # Tells GoReleaser to publish the final result
  # use_existing_draft: true # Important: picks up the draft from release-please
  # draft: false
  # mode: keep-existing
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
