name: Garni weather station
description: Weather data loader from Garni stations to Home Assistant
version: 1.3.0
slug: garni_weather_station
init: false
url: https://github.com/branislavholy/haAddOn/tree/main/weather
arch:
  - amd64
  - aarch64
startup: services
ports:
  8000/tcp: 8000
options:
  language: en
  uof: metric
  hostname: ''
  port: 1883
  username: 'branislav'
  password: ''
schema:
  language: list(en|sk)
  uof: list(metric|imperial)
  hostname: str
  port: int
  username: str
  password: password
