name: Garni weather station
description: Weather data loader from Garni stations to Home Assistant
version: 1.5.22
slug: garni_weather_station
init: false
url: https://github.com/branislavholy/haAddOn/tree/main/weather
arch:
  - amd64
  - aarch64
startup: services
ports:
  80/tcp: 80
options:
  language: en
  uof: metric
  hostname: ''
  port: 1883
  username: branislav
  password: ''
  log_level: info
schema:
  language: list(en|sk)
  uof: list(metric|imperial)
  hostname: str?
  port: int?
  username: str
  password: password
  log_level: list(debug|info|error)
