name: Garni weather station
description: Weather data loader from Garni stations to Home Assistant
version: 1.8.18
init: false
slug: garni_weather_station
url: https://github.com/branislavholy/haAddOn/tree/main/weather
arch:
  - amd64
  - aarch64
ports:
  80/tcp: 80
options:
  language: en
  temperature: °C
  precipitation: mm
  pressure: hPa
  speed: m/s
  ssl: false
  skipSslVerify: false
  hostname: ''
  port: 1883
  username: ''
  password: ''
  log_level: info
schema:
  language: list(en|sk|cz)
  temperature: list(°C|°F)
  precipitation: list(mm|in)
  pressure: list(hPa|mbar|mmHg|inHg)
  speed: list(m/s|km/h|mph|kn)
  ssl: bool
  skipSslVerify: bool
  hostname: str?
  port: int?
  username: str
  password: password
  log_level: list(debug|info|error|warning)
